### ISSUE TITLE
[객사오] 1장 p28 역할과 책임에 관해서

### ISSUE THREAD

**Issue by belljun3395** [JNU-econovation/java-ggun#4]
+ 여러 사람이 동일한 역할을 수행할 수 있다.
+ 역할은 대체 가능성을 의미한다.
+ 책임을 수행하는 방법은 자율적으로 선택할 수 있다.
+ 한 사람이 동시에 여러 역할을 수행할 수 있다.

저는 역할과 책임에 대해 읽어보다 역할과 책임이 우리가 사용하는 `인터페이스`가 아닌가 하는 생각을 하였습니다.
인터페이스 역시 객체에 동일한 메서드를 구현하는 것을 강제하고 
그 메서드는 자유롭게 구현 가능하며  
인터페이스를 통해 다형성을 구현할 수 있으니 비슷하다 생각하였습니다.

그렇다면 우리가 객체에 역할을 부여할 때 인터페이스를 사용하는 것이 좋을까요?
인터페이스는 어떠한 경우에 사용하는 것이 좋을까요?

**Comment by hwangdaesun** [comment]
글을 읽다가 인터페이스에 역할은 무엇일까? 라는 생각이 들어서 이것저것 찾아보았습니다.
제가 이해한게 맞다면, 개발자들끼리 협엽을 더 잘 할 수 있게 도와주는 목적이었습니다.
그렇다면, 인터페이스를 사용하는 순간은 인터페이스의 역할과 관계가 있지 않을까 라는 생각이 듭니다.
